// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WFUNO9pPG6N4CdZOIbKEiMjc2iZPGnw',
    appId: '1:70556919679:web:59de19cb585c9d8c965c4a',
    messagingSenderId: '70556919679',
    projectId: 'water-flood-iot',
    authDomain: 'water-flood-iot.firebaseapp.com',
    databaseURL: 'https://water-flood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flood-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq7TRlrs0TmJ-zoULF2FHchif77rsmEXg',
    appId: '1:70556919679:android:8a2e16b0e09de5c0965c4a',
    messagingSenderId: '70556919679',
    projectId: 'water-flood-iot',
    databaseURL: 'https://water-flood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flood-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSE7c70tXLlbMkPxBadzJ_JkS2jOVASo',
    appId: '1:70556919679:ios:c78ec97c59cd7e3e965c4a',
    messagingSenderId: '70556919679',
    projectId: 'water-flood-iot',
    databaseURL: 'https://water-flood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flood-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationWaterFlood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWSE7c70tXLlbMkPxBadzJ_JkS2jOVASo',
    appId: '1:70556919679:ios:c78ec97c59cd7e3e965c4a',
    messagingSenderId: '70556919679',
    projectId: 'water-flood-iot',
    databaseURL: 'https://water-flood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flood-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationWaterFlood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2WFUNO9pPG6N4CdZOIbKEiMjc2iZPGnw',
    appId: '1:70556919679:web:9d6fc74974807fcb965c4a',
    messagingSenderId: '70556919679',
    projectId: 'water-flood-iot',
    authDomain: 'water-flood-iot.firebaseapp.com',
    databaseURL: 'https://water-flood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flood-iot.firebasestorage.app',
  );
}
